---
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --check-only
        language: system
        types:
          - python

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types:
          - python
